### ISSUE TITLE
Feature request: Option to blacklist certain teleport locations

### ISSUE THREAD

**Issue by drejjmit** [SlashNephy/Divination#222]
Would it be possible to add an option to blacklist/ignore teleport locations in AetheryteLinkInChat? 
Such as Base Omicron, Tertium, Bestways Burrow and The Macarenses Angle?

**Comment by SlashNephy** [comment]
Hi!
Sorry for the late response. I just released v6.58.10.
[Release 6.58.10 · SlashNephy/Divination](https://github.com/SlashNephy/Divination/releases/tag/6.58.10)

Can you close the Issue once you are sure the issue has been resolved?

**Comment by drejjmit** [comment]
Everything seems to work during my testing 👍
Thank you for accepting my feature request.
