### ISSUE TITLE
Installation fails in Dalamud and download link on website does not work

### ISSUE THREAD

**Issue by kaizerfreak** [SlashNephy/Divination#438]
![image](https://github.com/SlashNephy/Divination/assets/17659956/61301bb3-6870-4822-8606-f345c93ef6dc)

Below button just redirects to the same page
![image](https://github.com/SlashNephy/Divination/assets/17659956/66a3427f-e357-4c06-94ae-abadb293eab3)

**Comment by SlashNephy** [comment]
Hi!

I apologize for any inconvenience. The issue was due to a failure in deploying to Cloudflare Pages.
It is now available for use without any problems.
