### ISSUE TITLE
Installation through Dalamud still not working

### ISSUE THREAD

**Issue by kaizerfreak** [SlashNephy/Divination#439]
![image](https://github.com/SlashNephy/Divination/assets/17659956/7221391d-79c8-46c4-8499-29b587d1bba9)

Downloading through the website works fine, but still having error installing through the in game installer.

**Comment by SlashNephy** [comment]
Hi.

Is this still happening? It appears Cloudflare blocks our requests. I've just tried relaxing the WAF rules.

**Comment by kaizerfreak** [comment]
Yes, the plugin installer still is getting an error. Is it working for you?

**Comment by kaizerfreak** [comment]
Okay, it looks like it's actually downloading, I am getting files in the installed plugins folder. But it is failing to load.

![image](https://github.com/SlashNephy/Divination/assets/17659956/69c9a60a-0efa-4ed8-8748-5d0fc15b6d3d)

![image](https://github.com/SlashNephy/Divination/assets/17659956/01132578-1acf-4b64-8521-1e88c5432a6b)

**Comment by SlashNephy** [comment]
How about changing Dalamud confuig to receive test builds?
https://goatcorp.github.io/faq/dalamud_troubleshooting.html#q-how-do-i-enable-plugin-test-builds

Some plugins are not working If you have not opted in to test builds.

**Comment by kaizerfreak** [comment]
Yes, I had that checked. It looks like I pulled the right version 0.1.0.1723 and it installed correctly, whereas previously I had 0.1.0.1255 as above. So I guess that's all done now.
