### ISSUE TITLE
FaloopIntegration no longer working

### ISSUE THREAD

**Issue by drejjmit** [SlashNephy/Divination#635]
You get connected but no S-ranks are ever shown. Did the API change?

**Comment by SlashNephy** [comment]
Hmmm, I recently got back into FFXIV and the plugin certainly doesn't seem to be working.

I'll look into it tomorrow.

**Comment by SlashNephy** [comment]
Fixed in 6.57.1. https://github.com/SlashNephy/Divination/commit/6dab5afb05c45510c7cf943c653f90a85d1760ae
