### ISSUE TITLE
AetheryteLinkInChat Feature request: integrate with Lifestream for world travel link

### ISSUE THREAD

**Issue by alyssadev** [SlashNephy/Divination#638]
Instead of showing aetheryte links for the home aetheryte teleport, it would be neat to instead show a link that triggers `/li <world>`, followed by the aetheryte link for when the user has arrived at that world

https://github.com/NightmareXIV/Lifestream

**Comment by SlashNephy** [comment]
Thanks for the request.

I plan to enhance the convenience of world travel.

**Comment by alyssadev** [comment]
Thank you, this works very well!
