### ISSUE TITLE
[AetheryteLinkInChat] Links to the zone Ultima Thule suggest teleporting to the world server Ultima first

### ISSUE THREAD

**Issue by alyssadev** [SlashNephy/Divination#648]
**Which plugin are you referring to?**
AetheryteLinkInChat

**Describe the bug**
A flag in the zone Ultima Thule suggests going to the world server Ultima:

![image](https://github.com/SlashNephy/Divination/assets/63546997/80ef7f0d-7810-43d4-9cfd-ad829144b2c5)

**To Reproduce**
1. This bug may be limited to the English client
2. Create a flag in the zone Ultima Thule and link it in the chat window with /echo.
3. AetheryteLinkInChat appends the path through the character's chosen city-state aetheryte to hop to Ultima

**Expected behavior**
The last link, to Reah Tahra/Abode of the Ea/Omicron, is all that should be present, not the hop to the city-state and teleportation to the world server Ultima.

**Comment by SlashNephy** [comment]
Thanks for the report!

It looks like world name extraction is not working. I'll try to fix it.

**Comment by Uriei** [comment]
Oh I didn't notice there was an issue already open for this, I took the advantage of doing a fix on my side, check if you like it and clean it if it's a bit dirty, for now it seems to work fine in my PC.
