### ISSUE TITLE
[AetheryteLinkInChat] Option for line break before teleport locations

### ISSUE THREAD

**Issue by drejjmit** [SlashNephy/Divination#651]
Would it be possible to have a setting for a line break (``\n``) before teleport alternatives?

![image](https://github.com/SlashNephy/Divination/assets/15526476/5fafb22f-33bf-4571-bcbd-22c5787d0a38)

I think it looks much cleaner and easier to navigate:

![image](https://github.com/SlashNephy/Divination/assets/15526476/2f2047c9-7638-49d1-b1d0-afbffe7487e0)

**Comment by SlashNephy** [comment]
Thanks for the request!

I'm busy at work this week, so I'll do it this weekend.

**Comment by SlashNephy** [comment]
Hi!
Sorry for the late response. I just released v6.58.10.
[Release 6.58.10 · SlashNephy/Divination](https://github.com/SlashNephy/Divination/releases/tag/6.58.10)

Can you close the Issue once you are sure the issue has been resolved?

**Comment by drejjmit** [comment]
Everything seems to work during my testing 👍
