### ISSUE TITLE
[AetheryteLinkInChat] Filtering of special characters in teleport shortcut

### ISSUE THREAD

**Issue by drejjmit** [SlashNephy/Divination#652]
Some users use the special characters for server names. That means it won't get matched with a server and the teleport won't get you there. Would it be possible to convert those to regular characters before trying to parse server names?

![image](https://github.com/SlashNephy/Divination/assets/15526476/9c087c76-9346-4f48-8932-3ee6d905987e)
![image](https://github.com/SlashNephy/Divination/assets/15526476/01082faa-18c6-4a12-8b79-1f7722e7ea3c)

 A
 B
 C
 D
 E
 F
 G
 H
 I
 J
 K
 L
 M
 N
 O
 P
 Q
 R
 S
 T
 U
 V
 W
 X
 Y
 Z

![image](https://github.com/SlashNephy/Divination/assets/15526476/040b55ac-9f99-4380-8452-bb4d3bb9d47d)


All in-game special characters are available [here](https://na.finalfantasyxiv.com/lodestone/character/22423564/blog/4393835)

**Comment by SlashNephy** [comment]
Thanks for the request!

I'm busy at work this week, so I'll do it this weekend.

**Comment by SlashNephy** [comment]
Hi!
Sorry for the late response. I just released v6.58.10.
[Release 6.58.10 · SlashNephy/Divination](https://github.com/SlashNephy/Divination/releases/tag/6.58.10)

Can you close the Issue once you are sure the issue has been resolved?
