### ISSUE TITLE
[FaloopIntegration] Support patch 7.x

### ISSUE THREAD

**Issue by SlashNephy** [SlashNephy/Divination#663]
Some data is hard coded and needs to be updated.
https://github.com/SlashNephy/Divination/blob/master/FaloopIntegration/Faloop/FaloopEmbedData.cs

**Comment by drejjmit** [comment]
New FATE doesn't seem to get reported in chat:
```
22:18:35.107 | DBG | [FaloopIntegration] Event "message" = "[{\"type\":\"mob\",\"subType\":\"report\",\"data\":{\"action\":\"spawn\",\"id\":{\"mobId\":\"ttokrrone\",\"worldId\":\"ragnarok\",\"zoneInstance\":1},\"data\":{\"zoneId2\":\"shaaloani\",\"zonePoiIds\":[1229],\"timestamp\":\"2024-07-01T20:15:34.966Z\",\"reporters\":[{\"id\":5186,\"name\":\"Ashelia Raithwall\"}],\"window\":1,\"stage\":null}}}]"
```
I'm on version v6.58.15.21 with these settings

![image](https://github.com/SlashNephy/Divination/assets/15526476/2f350495-6d84-476a-b51f-fec4adbf54b6)

**Comment by SlashNephy** [comment]
Faloop seems to manage pop locations by ID (called ZonePoiId). I just added new pop locations.
https://github.com/SlashNephy/Divination/commit/fa86367d99b34adff714b2b0187b4e144c5f4183

Ttokrrone's FATE should also display correctly.
