### ISSUE TITLE
[FaloopIntegration] Set <flag> without calling OpenMapWithMapLink

### ISSUE THREAD

**Issue by SlashNephy** [SlashNephy/Divination#667]
**Which plugin are you referring to?**
FaloopIntegration

**Please describe your feature request in detail.**
I recently added a button that allows you to copy and paste Faloop mob coordinates into chat.
However, when I call IGameGui#OpenMapWithMapLink and set <flag>, the map is opened.

It may be possible to set <flag> without opening the map by using AgentMap#SetFlagMapMarker defined in FFXIVClientStructs. (ref. https://github.com/SlashNephy/Divination/commit/23d8d6c4c35428412cd2a5c3f393bfae60db24be#r143858857)

**Comment by SlashNephy** [comment]
It seems that the coordinates to be passed to AgentMap#SetFlagMapMarker need some transformation.

The following code did not work. The coordinates seem to be slightly off.
```cs
var agent = AgentMap.Instance();
if (agent == null)
{
    return;
}

agent->SetFlagMapMarker(mob.TerritoryTypeId, mob.Map.RowId, new Vector3(mob.Coordinates.Value.X, 0, mob.Coordinates.Value.Y));
```

**Comment by Diyagi** [comment]
Ya, they are not normal coordinates you see in game, there was some discussion in dalamud discord a while ago abt this, apperently they are:

> mapX and mapY in that context are basically your 3D world coordinates rounded and converted to int
> \- Pohky

**Comment by Diyagi** [comment]
This also may help
https://github.com/xivapi/ffxiv-datamining/blob/master/docs/MapCoordinates.md

**Comment by Diyagi** [comment]
```c#
private Vector2 WorldToMap(Vector3 pos, ushort sizeFactor, short offsetX, short offsetY) {
  var scale = sizeFactor / 100f;
  var x = (10 - ((pos.X + offsetX) * scale + 1024f) * -0.2f / scale) / 10f;
  var y = (10 - ((pos.Z + offsetY) * scale + 1024f) * -0.2f / scale) / 10f;
  x = MathF.Round(x, 1, MidpointRounding.ToZero);
  y = MathF.Round(y, 1, MidpointRounding.ToZero);
  return new Vector2(x, y);
}
```

This is an example Pohky gave, `sizeFactor` and  `offsets` can all be found in the maps excel `ExcelSheet<Map>.Find(mapId)`

**Comment by Diyagi** [comment]
Subtracting `1024f` from the coordinates you get from `FaloopEmbedData` kinda places the marker right, theres still a bit of offset, i also tested this with only 2 places because it is the ones i have data to mock, so this offset might get bigger depending on the map.

**Comment by Diyagi** [comment]
Ok, got it, took me a while to notice, the coords from `FaloopEmbedData` are texture coordinates (2048x2048), i was doing things thinking they were world coordinates (im dumb).
We just need to do the reverse of [GetPixelCoordinates](https://github.com/xivapi/ffxiv-datamining/blob/master/docs/MapCoordinates.md) which is:
```c#
var x = (loc[0] - 1024f) * 100f / mob.Map.SizeFactor;
var y = (loc[1] - 1024f) * 100f / mob.Map.SizeFactor;
```

this yielded much better flags:
![image](https://github.com/SlashNephy/Divination/assets/9062212/b7acc461-0bf6-4020-8e0a-91e1d90e6d61)

**Comment by SlashNephy** [comment]
Thank you 😄
