### ISSUE TITLE
Fails to install via dalamud luncher

### ISSUE THREAD

**Issue by redskal01** [SlashNephy/Divination#675]
**Which plugin are you referring to?**
AetheryteLinkInChat

Fails to load after initial installation via dalamud luncher

![image](https://github.com/user-attachments/assets/88632982-7022-45ef-b02c-d0d142d47b88)

I got my get plugin testing builds ticked.
Instance id viewer works just fine but link in chat just fails to load when being installed

**Comment by DeadeyeN** [comment]
Same issue for me. I get this on AetheryteLinkInChat and Faloop.
