### ISSUE TITLE
[AetheryteLinkInChat] Payloads are in the middle of messages

### ISSUE THREAD

**Issue by Jaksuhn** [SlashNephy/Divination#678]
**Which plugin are you referring to?**
AetheryteLinkInChat

**Describe the bug**
I'd be surprised if this wasn't an intentional change but I'd at least like to know if it was to be sure. Last update seemed to have switched from appending the payloads to the end of the message to inserting them right after the maplink payload. This results in oddly broken up chat messages.

**To Reproduce**
receive any relay

**Expected behavior**
Pre v7.0.1.18 behaviour where ALIC payloads were appended to the end of the message

**Screenshots**
old:
![image](https://github.com/user-attachments/assets/5126d7d7-20fe-476a-912f-603d072738c5)

new:
![image](https://github.com/user-attachments/assets/74b5d0f1-348a-4406-9edd-2cc0e764285b)

**Comment by Diyagi** [comment]
Thats intentional, i found it to be more pleasing with the links after the maplink rather than in the end of the message (it also made easier for trains, since some conductors like to use funny messages in the relays).
I will open an PR to make this an option instead of enforcing.

**Comment by Jaksuhn** [comment]
Ah yeah I can sort of see the appeal when it comes to hunt train messages. Appreciate the option, thanks!
