### ISSUE TITLE
All Divination plugins broken in Dalamud v10.0.0.15

### ISSUE THREAD

**Issue by YsEmei** [SlashNephy/Divination#684]
Since no update has been pushed since #680 was merged, stg version has now hit Release and users on v10.0.0.15 or higher can't load your plugins.
Works fine on v10.0.0.14, but not on v10.0.0.15 or higher.

**Comment by SlashNephy** [comment]
I published a new release last week, but it did not seem to have been distributed correctly.
It was a CI/CD pipeline issue.
A new plugin version v7.0.2.0 is now available.
